image: Visual Studio 2017
version: 0.0.0.{build}
build_script:
- ps: .\ci\build-solution.ps1
test_script:
- ps: .\ci\run-test.ps1
artifacts:
- path: SumoLogic.Logging.Nuget\**.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: kf/eY/L/ncGs4CSm934M/nkr8ihhX7G3hMq+r7Fg+vBwoaGoTl8eHxyPVNVkRKSw
  on:
    appveyor_repo_tag: true