image: Visual Studio 2017
version: 0.0.0.{build}
build_script:
- ps: .\ci\build-solution.ps1
test_script:
- ps: .\ci\run-test.ps1
artifacts:
- path: SumoLogic.Logging.Nuget\**.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: +KndWSzRJjtBYCRtWrs9sWDgRfJAo0plxux/niYv6pp/nc8Pwg0/FjkPzfcM+hGs
  on:
    appveyor_repo_tag: true
